### ISSUE TITLE
tor module won't start 

### ISSUE THREAD

**Issue by arshiay** [hak5/wifipineapple-modules#86] opened 2019-12-15 05:43 UTC
hi 
tor module won't start at all 
pineapple nano
V = 2.6.2

**Comment by catatonicprime** [comment] 2019-12-16 17:17
This is a duplicate of [Issue 84](https://github.com/hak5/wifipineapple-modules/issues/84).

**Closed** 2019-12-16 17:42 UTC

**Comment by arshiay** [comment] 2019-12-17 13:16
hi
mine is not working on internal or sd 
please read carefully and then close issue closing issue not working

**Comment by catatonicprime** [comment] 2019-12-22 18:57
@arshiay I just want to make sure you understand this issue was closed because it's a duplicate. More information will be available on the previously opened issue (link above).
